start adding detection of the running vite server

diff --git a/commands/web/vite-serve b/commands/web/vite-serve
--- a/commands/web/vite-serve
+++ b/commands/web/vite-serve
@@ -29,6 +29,17 @@ if [ $CMD = start ]; then
   tmux new -s vite-sess -d
   tmux send "node node_modules/vite/bin/vite.js --host" C-m
   echo "Vite now serving $VITE_DIR"
+  # give it time to come all the way up.
+  sleep 10
+  # see if the port is actually in use. This will need
+  # to use the config variable when we have it; for now,
+  # assume the default port of 3000
+  curl -s localhost:3000 &>/dev/null
+  if [ $? -eq 0 ]; then
+    echo Vite dev server detected on port 3000
+  else
+    echo "ERROR: Vite server not detected on port 3000"
+  fi
 
 # stopping
 elif [ $CMD = stop ]; then
