Added some sanity checking to the command

diff --git a/commands/web/vite-serve b/commands/web/vite-serve
--- a/commands/web/vite-serve
+++ b/commands/web/vite-serve
@@ -6,15 +6,29 @@ VITE_DIR=${VITE_PROJECT_DIR:=frontend}
 CMD=${CMD:=start}
 
 if [ $CMD = start ]; then
+
+  # Make sure the project directory is actually there
+  if [ ! -d $VITE_DIR ]; then
+    echo "ERROR: js project directory $VITE_DIR was expected, not found"
+    exit 1
+  fi
+
   # make sure node_modules has linux and not mac code:
   cd $VITE_DIR
   pnpm install
+
+  # Is js project a Vite project?
+  if [ ! -d node_modules/vite ]; then
+    echo "ERROR: project in $VITE_DIR does not appear to be Vite-enabled"
+    exit 1
+  fi
 
   # create a background tmux session and tell it to run
   # our vite script
   tmux kill-session -t vite-sess 2>/dev/null
   tmux new -s vite-sess -d
   tmux send "node node_modules/vite/bin/vite.js --host" C-m
+  echo "Vite now serving $VITE_DIR"
 
 # stopping
 elif [ $CMD = stop ]; then
